In [ ]:
"""Dùng numpy để tạo các ma trận sau::

	array([[ 0,  1,  2,  3,  4,  5],
	       [10, 11, 12, 13, 14, 15],
	       [20, 21, 22, 23, 24, 25],
	       [30, 31, 32, 33, 34, 35],
	       [40, 41, 42, 43, 44, 45],
	       [50, 51, 52, 53, 54, 55]])


	array(  [[0., 0., 0., 0., 0.],
			 [2., 0., 0., 0., 0.],
			 [0., 3., 0., 0., 0.],
			 [0., 0., 4., 0., 0.],
			 [0., 0., 0., 5., 0.],
			 [0., 0., 0., 0., 6.]])
"""

In [4]:
import numpy as np

In [21]:
A = np.array([[0, 1, 2, 3, 4, 5]])
B = A + 10
C = A + 20
D = A + 30
E = A + 40
F = A + 50

In [22]:
X = np.concatenate((A, B, C, D, E, F), axis=0); X 

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [24]:
G = np.array([[0., 0., 0., 0., 0.],
              [2., 0., 0., 0., 0.],
              [0., 3., 0., 0., 0.],
              [0., 0., 4., 0., 0.],
              [0., 0., 0., 5., 0.],
              [0., 0., 0., 0., 6.]]); G

array([[0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 6.]])